// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqgscvucmnuicgxyooti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZ3NjdnVjbW51aWNneHlvb3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODU2MjIsImV4cCI6MjA3MDA2MTYyMn0.mbq4EAGPkqz2RGM1KKObU8w1TJomTfujKoYZa9GBhhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});